on:
  workflow_dispatch: {}
jobs:
  build:
    permissions:
      packages: write
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: "true"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          provenance: true
          sbom: true
          push: true
          tags: ghcr.io/${{ github.repository }}/zettarepl-build
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Get RPMS
        run: |
            docker run --detach --rm --platform linux/amd64 --name zettarepl-build ghcr.io/${{ github.repository }}/zettarepl-build /bin/bash -c 'while true; do echo -n .; sleep 1; done'
            docker cp zettarepl-build:/root .
            docker stop zettarepl-build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "root/*.rpm,root/*.deb"